### ISSUE TITLE
Include reading routine for LE3 WL correlation functions

### ISSUE THREAD

**Issue by gcanasherrera** [euclidlib/euclidlib#4]
To discover who is the developer behind that PF, and ask for contribution.

Alternatively, get a synthetic file and create the reading routine.

**Comment by gcanasherrera** [comment]
@FelicitasKeil has made an implementation in a branch. Could you do the PR?

**Comment by FelicitasKeil** [comment]
Hello @gcanasherrera, I added a unit test similar to the other unit tests and it is passing. I also have two questions.

1. This reads the \$\xi_\pm$  for the 2 point correlation in WL. Martin Kilbinger also sent me a fits file for the COSEBIs for example. Is this all we want for now? The Cloe gitlab issue is titled "2PCF - WL", but the description also mentions other fits files.

2. Then I have a question related to the "philosophy" of euclidlib. For now, I am including the file `photo_data.py`in the `photo` folder written by Martin Kilbinger and Jingwei Wang who are credited in the same file. Does this work for euclidlib? Otherwise we could shorten this file, because not everything is used (yet) or integrate it somewhere else.

Otherwise, I can open a pull request.
